debug 4

diff --git a/.github/workflows/proper_unicode_check.yml b/.github/workflows/proper_unicode_check.yml
--- a/.github/workflows/proper_unicode_check.yml
+++ b/.github/workflows/proper_unicode_check.yml
@@ -10,13 +10,17 @@ jobs:
     - uses: actions/checkout@v4
     - name: Check all files are OK wrt encoding    
       run: |
+        set +e # continue on error
+        
         all_files_OK=0
         for file_to_check in $(git ls-files '*.htm*')
         do echo Processing $file_to_check
+                
         iconv -f utf-8 -t utf-8 $file_to_check > /dev/null 2>error_text       
         echo return code = $? and error text:
         cat error_text
         echo ====
+        
         if [ -s error_text ]
         then  echo OK
         else
@@ -24,4 +28,8 @@ jobs:
         all_files_OK=1
         fi
         done
+        set -e # don't continue on error
+        
         test $all_files_OK == 0
+        
+        
